spring.application.name=ProductSearchApp

server.port=2027

spring.datasource.url=jdbc:mysql://localhost:3306/skill
spring.datasource.username=root
spring.datasource.password=Uday@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect